#! /bin/bash

# 开始执行部署PN-9900程序
echo -e "\e[1;32m开始部署PN-9900程序 \e[0m"

# 获取认证结果
resultJWT=$(curl --location --request POST 'http://127.0.0.1:9000/api/auth' --header 'Content-Type: text/plain' --data '{  "password": "Pn123456",  "username": "admin"}')
echo $resultJWT
# 解析json
parse_json() {
  echo "${1//\"/}" | sed "s/.*$2:\([^,}]*\).*/\1/"
}

# 获取token认证
value=$(parse_json $resultJWT "jwt")
# 获取compose.yml文件内容并转义换行符

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result1=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/1/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/1?endpointId=1' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 1, \"StackFileContent\": \"${result1}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 60

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result2=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/2/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/2?endpointId=2' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 2, \"StackFileContent\": \"${result2}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 60

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result3=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/3/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/3?endpointId=3' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 3, \"StackFileContent\": \"${result3}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 60

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result4=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/4/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/4?endpointId=4' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 4, \"StackFileContent\": \"${result4}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 60

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result6=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/6/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/6?endpointId=6' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 6, \"StackFileContent\": \"${result6}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 60

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result7=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/7/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/7?endpointId=7' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 7, \"StackFileContent\": \"${result7}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 60

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result8=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/8/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/8?endpointId=8' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 8, \"StackFileContent\": \"${result8}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 60

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result9=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/9/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/9?endpointId=9' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 9, \"StackFileContent\": \"${result9}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 60

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result15=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/15/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/15?endpointId=15' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 15, \"StackFileContent\": \"${result15}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 60

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result25=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/25/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/25?endpointId=25' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 25, \"StackFileContent\": \"${result25}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 60

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result26=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/26/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/26?endpointId=26' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 26, \"StackFileContent\": \"${result26}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 720

echo -e "\e[1;32m开始执行base脚本 \e[0m"
result31=$(sed s/$/"\\\n"/ /njpn/PN-9900/deploy/portainer/data/compose/31/docker-compose.yml | tr -d '\n')
echo "curl --location --request PUT -w %{http_code} 'http://127.0.0.1:9000/api/stacks/31?endpointId=31' --header 'Authorization: Bearer ${value}' --header 'Content-Type: application/json' --data '{ \"id\": 31, \"StackFileContent\": \"${result31}\",\"Env\": [],\"Prune\": false }'" | sh
if [ $? -eq 0 ]; then
  echo -e "\e[1;32m执行base脚本成功 \e[0m"
else
  echo -e "\e[1;31m执行base脚本失败 \e[0m"
  exit 1
fi
sleep 60
