server:
 port: 8088
spring:
 datasource:
   name: test
   url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=UTC
   username: root
   password: fnst-3d3k
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.cj.jdbc.Driver
 aop:
   proxy-target-class: true
 redis:
   host: 127.0.0.1
   port: 6379
   password:
   lettuce:
     shutdown-timeout: 5000ms
   jedis:
     pool:
       max-active: 8
       max-wait: -1ms
       min-idle: 0
       max-idle: 8

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.demo.entity

#pagehelper plugin configuration
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
