server:
  port: 8088
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: fnst-3d3k
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    proxy-target-class: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      shutdown-timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
  #RabbitMQ 配置信息
  rabbitmq:
    host: 146.56.220.117
    port: 5672
    username: jimh
    password: jimh
    virtual-host: /jimh
    connection-timeout: 15000
    publisher-returns: true
    template:
      mandatory: true
    #消费端配置
    listener:
      simple:
        #消费端
        concurrency: 5
        #最大消费端数
        max-concurrency: 10
        #自动签收auto  手动 manual
        acknowledge-mode: manual
        #限流（海量数据，同时只能过来一条）
        prefetch: 1

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.demo.entity

#pagehelper plugin configuration
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
